#+title: Simon's Emacs Configuration File
#+PROPERTY: header-args:emacs-lisp :tangle /home/simon/.emacs.d/init.el :mkdirp yes
#+startup: hidestars

All that follows is based on the wonderful work of System Crafters. 
Whenever you edit =config.org= in Emacs and save it, it updates files in your .emacs.d directory.

See the [[https://orgmode.org/manual/Extracting-Source-Code.html][Org Manual]] for details and alternatives.


** Required environmental variables
The example shown below shows the settings for my SYSTEM76 setup.
These are typically in your .bashrc or `.bash_profile'.

#+begin_src bash :tangle no

# (also export MY_NAME=SYSTEM76 as previously set)
export USER_EMACS_DIRECTORY="/home/simon/.emacs.d"
export ENV_FILE="/home/simon/Me/secrets/serviceEnv.txt"
# set up the bib file home for emacs to use.
export BIB_HOME="/home/simon/sync/primary/dotfiles/latex/templates/bibFile/refs.bib"
# set up the repo data file path.
export REPO_LIST="/home/simon/sync/primary/dotfiles/git/repoList.csv"
# set up the projectile project search paths.
export PROJECTILE_PATHS="/home/simon/Downloads/github:5,/home/simon/sync/primary/Adventures:5,/home/simon/sync/primary/dotfiles:5"

# now set up other useful environmental variables that emacs might
# need. These will be saved into ~/Me/secrets/serviceEnv.txt and
# loaded at startup.
# Set defaults for python home environment. (used in emacs)
export CONDA_PREFIX="/home/simon/anaconda3"
export CONDA_DEFAULT_ENV="base"
export WORKON_HOME="/home/simon/anaconda3/envs/"

export JUPYTER_WORKING_DIRECTORY="/home/simon"
export JUPYTER_ANACONDA_ENVIRONMENT="gpt4"

#+end_src


** External dependencies
Make sure you have the following external dependencies:

|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
|                      |                                        |                      |                         |
| Dependency           | Install expression                     | Associated mode      | Additional info-look    |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| imagemagik           | sudo apt install                       | Global               | Convert image files and |
|                      | imagemagik                             |                      | other goodies.          |
|----------------------+----------------------------------------+----------------------+-------------------------|
| latex                | sudo apt install                       | projectile           | fast search tool for    |
|                      | silversearcher-ag                      |                      | text files              |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| texlive-full         | sudo apt install                       | tex-mode             | fast search tool for    |
|                      | texlive-full                           |                      | text files.             |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| pandoc               | sudo apt install                       | writing modes        | convert/manage latex,   |
|                      | pandoc                                 |                      | markdown and others     |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| taplo                | cargo install taplo-cli --features lsp | toml-mode            | functionality for       |
|                      |                                        |                      | toml files.             |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| markdownlint-cli     | npm install -g                         | flymake-markdownlint | flymake plugin to       |
|                      | markdownlint-cli                       |                      | lint markdown.          |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| marksman             | sudo snap install marksman             | markdown-mode        | tools for markdown.     |
|----------------------+----------------------------------------+----------------------+-------------------------|
| texlab               | sudo apt install                       | tex-mode             | tex language server     |
|                      | texlab                                 |                      | for eglot.              |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| git-man              | sudo apt install                       | magit                | Use git manual with     |
|                      | git-man                                |                      | magit.                  |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| shfmt                | sudo apt install                       | bash-ts-mode         | format bash scripts.    |
|                      | shfmt                                  |                      |                         |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| bash-language-server | snap install                           | bash-ts-mode         | LSP for bash-ts-mode    |
|                      | bash-language-server                   | shell-script-mode    | with eglot.             |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| ruff        (1 of 2) | pip install ruff                       | python-ts-mode       | Python language server  |
|                      |                                        |                      | (linting/ formatting)   |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| basedpyright(2 of 2) | pip install                            | python-ts-mode       | Python language server  |
|                      | basedpyright                           |                      | (docs/ navigation)      |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| vega                 | npm install -g vega                    | vega-view            | allows edit and         |
|                      | vega-lite vega-cli                     |                      | generation of vega      |
|                      |                                        |                      | visuals in Emacs.       |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| shellcheck           |                                        | bash-mode            | lint bash code.         |
|                      | cabal (to install                      |                      |                         |
|                      | from source)                           |                      |                         |
|                      | add to path:                           |                      |                         |
|                      | export PATH= \                         |                      |                         |
|                      | "$PATH:/home/simon/                    |                      |                         |
|                      | .cabal/bin"                            |                      |                         |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| png                  | npm install -g                         | vega-view            | generate png rather     |
|                      | canvas                                 |                      | than svg - more         |
|                      |                                        |                      | efficient for dealing   |
|                      |                                        |                      | with thousands of       |
|                      |                                        |                      | data points.            |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| php & php-pgsql      | sudo apt install                       | sql-mode             | integrate postgres to   |
|                      | php php-pgsql                          |                      | web page.               |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| postgres             | sudo apt install                       | sql-mode             | Open source database.   |
|                      | postgresql                             |                      |                         |
|                      | doc-postgresql                         |                      |                         |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| pq                   | sudo apt-get install                   | sql-mode             | library for interacting |
|                      | postgresql libpq-dev                   |                      | with postgres           |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| pgFormatter          |                                        | sql-mode             | format sql code for     |
|                      |                                        |                      | postgresql.             |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| ss                   | sudo apt install ss                    | loadbalancer         | check for used ports    |
|                      | (if not installed by                   |                      | on the system.          |
|                      | default)                               |                      |                         |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| emacswiki            | cd .crafted-emacs                      |                      | The emacs wiki is       |
|                      | git clone                              |                      | full of useful          |
|                      |                                        |                      | functionality.          |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|
| Hunspell             | sudo apt install                       | dictionary           |                         |
|                      | hunspell                               |                      |                         |
|                      | hunspell-en-au                         |                      |                         |
|                      |                                        |                      |                         |
|----------------------+----------------------------------------+----------------------+-------------------------|

[[https://github.com/koalaman/shellcheck][shellcheck]]      
[[https://github.com/darold/pgFormatter/tree/master][pgFormatter]]  
[[https://github.com/emacsmirror/emacswiki.org.git][emacswiki]]  

** Image magik security policy update.
Remember to change the security policies in image magik to allow production of pdfs.
The security policy file is located somewhere like:  /etc/ImageMagick-6/ or /etc/ImageMagick/
This is needed to ensure the latex rendering system has something to use to generate PDFs.

Change this:
#+begin_src xml :tangle no

<policy domain="coder" rights="none" pattern="PDF" />

#+end_src
to this:
#+begin_src xml :tangle no

<policy domain="coder" rights="read|write" pattern="PDF" />

#+end_src


** Loading custom files with early-init.el and init.el

The files below provide additional functionality in my emacs setup.
These are all in =.emacs.d/custom-modules/=

*** Tangling to early-init.el

Define settings for =early-init.el=.

#+begin_src emacs-lisp :tangle ./early-init.el
;; early-init.el --- Emacs early initialization -*- lexical-binding: t; no-byte-compile: t -*-

;;; Commentary:
;; Work that is done before Emacs can be initialised.
;; All paths + package management + GC + native-comp now live here.

;;; Code:

;; === Base file paths + MY_NAME support ===
(setq user-emacs-directory
      (or (getenv "USER_EMACS_DIRECTORY")
          (expand-file-name "~/.emacs.d/")))
   

(defvar envvar/SYSTEM_NAME
  (or (getenv "MY_NAME") "INFODYNAMICS")
  "The name of the system on which we are currently running Emacs.")

;; === NO-LITTERING paths + PACKAGE SETUP (all early) ===

(defvar no-littering-var-directory
  (expand-file-name (concat "var/" envvar/SYSTEM_NAME "/")
                    user-emacs-directory))

(defvar no-littering-etc-directory
  (expand-file-name (concat "etc/" envvar/SYSTEM_NAME "/")
                    user-emacs-directory))

;; Force package.el to use our clean location from the VERY beginning
;; (Directory where ELPA/MELPA packages are installed.)
(setq package-user-dir
      (expand-file-name "elpa/" no-littering-var-directory))

;; Redirect native-comp cache
(setq my-paths/eln-cache
      (expand-file-name "eln-cache/" no-littering-etc-directory))
(when (and (fboundp 'startup-redirect-eln-cache)
           (boundp 'my-paths/eln-cache))
  (message "eln-cache file path set.")
  (startup-redirect-eln-cache my-paths/eln-cache))
  
  ;; Load path configuration (single source of truth)
(load-file (expand-file-name "custom-modules/path-support.el" user-emacs-directory))

;;;; UI configuration
(add-to-list 'default-frame-alist '(background-color . "#1B152D"))
(add-to-list 'default-frame-alist '(foreground-color . "#EEEEEC"))
(push '(tool-bar-lines . 0) default-frame-alist)
(push '(menu-bar-lines . 0) default-frame-alist)
(push '(vertical-scroll-bars) default-frame-alist)
(push '(mouse-color . "white") default-frame-alist)

;;;; Garbage collection, font & eln caching
(setq gc-cons-threshold (* 50 1000 1000))
(setq inhibit-compacting-font-caches t)
(setq comp-speed 1)
(setq load-prefer-newer t)
(setq package-native-compile t)
(setq native-comp-async-report-warnings-errors nil)
;;(setq package-enable-at-startup nil)


(provide 'early-init)
;;; early-init.el ends here
#+end_src

#+RESULTS:
: early-init

In your configuration you can set any Emacs configuration variable, face attributes, themes, etc as you normally would.
See the README.org file in this repository for additional information.


*** Tangle to init.el

General principle is that any default settings not set here (so set in the modules from the modules folder in .emacs.d and in the custom modules folder in .crafted-emacs) will be set from environmental variables expressed here and then used via the native custom support in emacs (=defcustom= and =defgroup=).  Here we either set those environmental variables or get existing environmental variables that are to be used in emacs.

This means all variables with external origins in emacs are specified here.

#+begin_src emacs-lisp :tangle ./init.el
  ;; init.el -- Simon's Emacs user customization file -*- lexical-binding: t; -*-

  ;;; Commentary:
  ;; This file is generated from config.org.  If you want to edit the
  ;; configuration, DO NOT edit init.el, edit config.org, instead.

  ;;; Code:

  ;; Load logging functionality
  (require 'path-support)

  (load-file (expand-file-name "custom-modules/system-tools/logging-config.el" user-emacs-directory))

  (require 'logging-config)

  ;; === PACKAGE ARCHIVES (MELPA now guaranteed) ===
  (require 'package)
  (setq package-archives
        '(("gnu" . "https://elpa.gnu.org/packages/")
          ("nongnu" . "https://elpa.nongnu.org/nongnu/")
          ("melpa" . "https://melpa.org/packages/")
          ("elpa-devel" . "https://elpa.gnu.org/devel/")))
  (setq package-archive-priorities
        '(("gnu" . 2)
          ("nongnu" . 1)
          ("melpa" . 0)
          ("elpa-devel" . 0)))
  (package-initialize)

  ;; === Robust use-package bootstrap ===
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
  (require 'use-package)
  (eval-and-compile
    (setq use-package-always-ensure t
          use-package-expand-minimally t))

  (defvar epg-gpg-program "/usr/bin/gpg")


  (defvar my/required-packages
  '(markdown-mode          ; needed by rustic, aidermacs, etc.
    rustic
    eglot
    corfu
    treesit-fold
    ;; add any other packages you consider essential here
    ))

  (dolist (pkg my/required-packages)
  (unless (package-installed-p pkg)
    (message "Installing missing core package: %s" pkg)
    (package-install pkg)))

  (menu-bar-mode -1)
  (define-key input-decode-map [C-tab] [control-tab])
  (global-set-key [control-tab] 'menu-bar-mode)

  (customize-set-variable 'initial-major-mode 'fundamental-mode)

  (use-package menu-keys-support
    :ensure nil
    :load-path "custom-modules/")

  (use-package lang-prog-mode
    :ensure nil
    :load-path "custom-modules/prog-mode/")

  ;; 2. Compile-angel — must come immediately after the custom modules
  ;;    (this was the original Step 3 that you had before we moved paths)
  (use-package compile-angel
    :demand t
    :config
    (setq compile-angel-verbose t
          compile-angel-enable-byte-compile nil
          compile-angel-enable-native-compile t)
    (compile-angel-on-load-mode 1)
    (add-hook 'emacs-lisp-mode-hook #'compile-angel-on-save-local-mode)
    (add-hook 'after-init-hook
              (lambda ()
                (when (get-buffer "*Compile-Log*")
                  (bury-buffer "*Compile-Log*")))))

  ;; 3. Everything from your original Step 6 onward is unchanged
  (defvar comp-speed 1 "Set native compilation.")
  (setq comp-speed 1)

  ;; Ensure that quitting only occurs once Emacs finishes native compiling,
  ;; preventing incomplete or leftover compilation files in `/tmp`.
  (defvar native-comp-async-query-on-exit t "Ensure that quitting only occurs once Emacs finishes native compiling.")
  (setq native-comp-async-query-on-exit t)
  (setq confirm-kill-processes t)

  ;; ensure we can control how minor modes are shown in the modeline. 
  (use-package delight)

  ;;;; Set up logging
  (require 'system-tools)

  (log/debug :fn 'init
             :msg "loaded system tools."
             :obj user-emacs-directory)

  (defvar my/REPO_LIST nil"The path to a list of git projects on the system.")
  (setq my/REPO_LIST (getenv"REPO_LIST"))

  ;; This is the way we define a custom variable and add it to a group.
  ;; (defcustom var-name default-value doc-string
  ;;  :type 'type
  ;;  :group 'group)

  (use-package bind-key)
  (use-package helpful :ensure t)

  ;;; imports and declarations
  (require 'bind-key)                                                              ; if you use any :bind variant
  (require 'elisp-packages)

  ;; ensure the correct org-mode is sourced.
  ;; install the org package before it is used - otherwise it causes conflict.
  ;; (add-to-list
  ;;  'load-path
  ;;  (expand-file-name "custom-modules/org-support.el" user-emacs-directory))
  (require 'org-support)

  ;; ensure tangling functionality is set up with org mode.
  (add-hook
   'org-mode-hook
   (lambda ()
     (add-hook 'after-save-hook 'org-babel-tangle
               'run-at-end
               'only-in-org-mode)))

  (log/info :fn 'init
            :msg "----Begin init.el processing----"
            :obj t)


#+end_src

**** Load environmental variables

#+begin_src emacs-lisp :tangle ./init.el

;;; Load current environmental variables
  (defun load-environment-variables-from-file (file-path)
    "Load environment variables from a file specified by FILE-PATH."
    (with-temp-buffer
      (insert-file-contents file-path)
      (goto-char (point-min))
      (while (not (eobp))
        (let ((line
               (buffer-substring-no-properties
                (line-beginning-position) (line-end-position))))
          (when (string-match "\\([^=]+\\)=\\(.*\\)" line)
            (let ((key (match-string 1 line))
                  (value (match-string 2 line)))
              (setenv key value))))
        (forward-line 1))))

  (let ((envFile  (getenv "ENV_FILE")))
    (log/debug :fn 'init
               :msg "Load environmental variables from file."
               :obj envFile)
    (load-environment-variables-from-file envFile))

#+end_src

**** Set up path management and Org

 [[file:./custom-modules/path-support.el][Packages to set and manage paths needed for emacs]]
  - [[https://github.com/emacscollective/no-littering/blob/main/no-littering.el][no-littering]]            Keep your paths tidy.
  - [[https://www.emacswiki.org/emacs/RecentFiles][recentf]]                 Recentf is a minor mode that builds a list of recently opened files.
 [[file:./custom-modules/org-support.el][Org packages & configuration]]
  - org
  - org-contrib
  - org-contacts
  - google-contacts
  - [[https://github.com/awth13/org-appear][org-appear]]              Toggle the visibility of some Org elements.
  - [[https://github.com/Fuco1/org-pretty-table][org-pretty-table]]        Prettyfy org tables.
  - org-pretty-tags
  - org-roam 

 [[file:./custom-modules/defaults-config.el][Custom default configuration]]


#+begin_src emacs-lisp :tangle ./init.el

;;; Initial phase.
(log/info :fn 'init
          :msg "----Begin loading base functionality from defaults-config.----"
          :obj t)

(require 'defaults-config)
;; setup save histories.
(savehist-mode 1)
(setq history-length t)
(setq history-delete-duplicates t)
(setq savehist-save-minibuffer-history 1)
(setq savehist-additional-variables
      '(kill-ring search-ring regexp-search-ring))

;; Load the custom file if it exists.  Among other settings, this will
;; have the list `package-selected-packages', so we need to load that
;; before adding more packages.  The value of the `custom-file'
;; variable must be set appropriately, by default the value is nil.
;; This can be done here, or in the early-init.el file.
;; (filepath set to etc in no-littering config.)
(when (and custom-file (file-exists-p custom-file))
  (load custom-file nil 'nomessage))


(log/info :fn 'init
          :msg "----Load of base functionality complete----"
          :obj t)

#+end_src


**** IDE type functionality

 [[file:./custom-modules/custom-ide-config.el][Packages for IDE functionality]]
  -  [[https://github.com/editorconfig/editorconfig-emacs][editorconfig]]           Expose additional configuration options for an IDE in a clear way.
  -  [[https://github.com/Malabarba/aggressive-indent-mode][aggressive-indent]]      Keep your code correctly indented as you type.
  -  [[https://github.com/AndreaCrotti/yasnippet-snippets][yasnippet-snippets]]     A collection of yasnippets.
  -  [[https://github.com/jacktasia/dumb-jump][dumb-jump]]              A "jump to definition" package that favors "just working".

 [[file:./custom-modules/treesit-support.el][Packages and configuration for Tree-sitter]]

 [[file:./custom-modules/undo-tree-support.el][Packages and configuration for undo-tree]
  -  [[https://gitlab.com/tsc25/undo-tree/-/blob/master/undo-tree.el][undo-tree]]              Save undo histories and access them in an intuitive way.

#+begin_src emacs-lisp :tangle ./init.el

;; IDE configuration.
(require 'treesit-support)
(require 'undo-tree-support)

#+end_src

**** UI enhancements

 [[file:./custom-modules/elisp-packages.el][Packages for base libraries for emacs lisp]]
  - [[https://github.com/magnars/s.el][ s.el]]                   String manipulation library
  -  [[https://github.com/magnars/dash.el][dash.el]]                A modern list API for Emacs. No 'cl required.

 [[file:./custom-modules/completion-support.el][Packages for Completion functionality]]
  -  [[https://github.com/minad/cape][cape]]                   Cape provides Completion At Point Extensions.
  -  [[https://github.com/minad/consult][consult]]                Consulting completing-read.
  -  [[https://github.com/minad/corfu][corfu]]                  Corfu enhances in-buffer completion with a small completion popup.
  -  [[https://codeberg.org/akib/emacs-corfu-terminal][corfu-terminal]]         Corfu popup on the terminal.
  -  [[https://github.com/oantolin/embark][embark]]                 Emacs Mini-Buffer Actions Rooted in Keymaps.
  -  [[https://github.com/oantolin/embark/blob/master/embark-consult.el][embark-consult]]         Use embark to configure the results provided by the consult completing read package.
  -  [[https://github.com/minad/marginalia][marginalia]]             Add marginalia to minibuffer completions.
  -  [[https://github.com/oantolin/orderless][orderless]]              Provides an orderless completion style that divides the pattern into space-separated components.
  -  [[https://github.com/minad/vertico][vertico]]                VERTical Interactive COmpletion.
  -  [[https://github.com/d12frosted/flyspell-correct][flyspell-correct]]       Generic interface to access flyspell.
  -  [[https://gitlab.com/OlMon/consult-flyspell][consult-flyspell]]       Integrate flyspell with consult.
  -  [[https://github.com/mohkale/consult-yasnippet][consult-yasnippet]]      A consulting-read interface for yasnippet.

 [[file:./custom-modules/ui-config.el][Packages for User Interface functionality]]
  -  imenu-list
  -  nerd-icons
  -  elisp-demos
  -  helpful
  -  [[https://www.emacswiki.org/emacs/BookmarkPlus][Bookmark+]]              Improved bookmarking; loaded at the end of the process because of its many dependencies.
  -  [[https://www.emacswiki.org/emacs/DiredPlus][Dired+]]                 Improved Dired; loaded at the end of the process because of its many dependencies.
  -  [[https://www.emacswiki.org/emacs/InfoPlus][Info+]]                  Additional functionality for navigating help/Info files in emacs.

 [[file:./custom-modules/writing-config.el][Packages for Tex and other document production]]
 [[file:./custom-modules/system-tools/system-tools.el][Additional functionality for use with user functions in emacs]]
 [[file:./custom-modules/theme-support.el][Packages and config for theming]]
    
 [[file:./custom-modules/project-support.el][Packages and config for project management]]

#+begin_src emacs-lisp :tangle ./init.el

  ;;; Configuration phase

  (require 'theme-support)
  (require 'project-support)
  (require 'completion-support)

#+end_src

 [[file:./custom-modules/speedbar-support.el][Custom Speedbar support]]

 [[file:./custom-modules/modeline-support.el][Custom Modeline support]]

 [[file:./custom-modules/vterm-support.el][Custom vterm support]]
 
 [[file:./custom-modules/spreadsheet-support.el][Custom Spreadsheet support]]
  - [[https://gitlab.com/dto/cell-mode][Cell-Mode]]               A spreadsheet with cell-mode (see the emacs conference [[https://emacsconf.org/2019/talks/18/][for 2019]])

#+begin_src emacs-lisp :tangle ./init.el

  ;; user interface
  (require 'ui-config)
  (require 'ibuffer-support)
  (require 'tabline-support)
  (require 'speedbar-support)
  (require 'modeline-support)
  (require 'vterm-support)
  (require 'spreadsheet-support)

  ;; activate the logging view. 
  (use-package logging-view-mode
    :ensure nil  ; Local file, not a package
    :load-path my-paths/logging-view-mode)

#+end_src

 [[file:./custom-modules/ide-config.el][Base configuration for the IDE]]
 [[file:./custom-modules/org-support.el][Config for Org-mode]]
 [[file:./custom-modules/writing-config.el][Config for Tex and other document production support]]

#+begin_src emacs-lisp :tangle ./init.el

  ;; Flymake configuration
  (require 'flymake-config)

  ;; Base IDE configuration.
  (require 'ide-config)

  ;; Debugger support
  (require 'debugger-support)

  ;; Handle writing config (Latex and the like)
  (require 'writing-config)

  ;; Markdown support
  (require 'markdown-support)

#+end_src

 [[file:./custom-modules/fileFormat-support.el][Support for file formatting]]

#+begin_src emacs-lisp :tangle ./init.el

  ;; Additional file format support.
  (require 'fileFormat-support)

#+end_src

 [[file:./custom-modules/vc-support.el][Packages and configs for Version Control]]


#+begin_src emacs-lisp :tangle ./init.el

  ;; version control
  (require 'vc-support)

#+end_src


**** Set up the IDE functionality
These links take you to the languages set up with Emacs.
 [[./custom-modules/prog-mode/lang-prog-mode.el][IDE language: functionality common across all languages]]
 
 [[file:./custom-modules/prog-mode/lang-lisp.el][IDE language: Lisp varietals]]
 [[file:./custom-modules/prog-mode/lang-rust.el][IDE language: Rust setup]]
 [[file:./custom-modules/prog-mode/lang-python.el][IDE language: Python setup]]
 [[file:./custom-modules/prog-mode/lang-q.el][IDE language: Q setup]]
 [[file:./custom-modules/prog-mode/lang-systemd.el][IDE language: Systemd setup]]
 [[file:./custom-modules/prog-mode/lang-web.el][IDE language: web setup]]
  -  [[https://github.com/emacs-php/apache-mode][apache-mode]]            Emacs major mode for editing apache2 config files.
  -  [[https://github.com/emacs-php/robots-txt-mode][robots-txt-mode]]        Emacs major mode for editing [[http://www.robotstxt.org/robotstxt.html][robots.txt]]. This mode supports well-known [[https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt?visit_id=638447716778136466-858157116&rd=1][extension by Google]] and [[https://datatracker.ietf.org/doc/html/draft-rep-wg-topic-00][RFC Draft]].
  -  [[https://web-mode.org][web-mode]]               An emacs major-mode for editing web templates containing embedded parts. (eg HTML embedding CSS / JavaScript).
  
 [[file:./custom-modules/prog-mode/lang-bash.el][IDE language: Bash setup]]
 [[file:./custom-modules/prog-mode/lang-docker.el][IDE language: Docker setup]]
  -  [[https://github.com/Silex/docker.el][docker.el]]              Manage docker from Emacs.
  -  [[https://github.com/meqif/docker-compose-mode][docker-compose]]         Completions for editing docker compose files.


#+begin_src emacs-lisp :tangle ./init.el

  ;; programming languages
  (require 'lang-prog-mode)
  (require 'lang-bash)
  (require 'lang-matlab)
  (require 'lang-docker)
  (require 'lang-lisp)
  (require 'lang-python)
  (require 'lang-q)
  (require 'lang-rust)
  (require 'lang-systemd)
  (require 'lang-vega)
  (require 'lang-web)

#+end_src

 [[file:./custom-modules/db-support.el][Database support]]:          Support needed for sql-mode and PostgreSQL.
  - [[https://github.com/anse1/emacs-libpq][emacs-libpq]]             An Emacs 25 module for accessing PostgreSQL via the libpq client library.
  - [[https://github.com/purcell/sqlformat][sqlformat]]               Provides commands and a minor mode for easily reformatting SQL using external programs.

 Integrated external functions:
  - [[https://www.postgresql.org/][postgresql]]              Great open-source database.
  - [[https://github.com/darold/pgFormatter][pgFormatter]]             Formats postgresql code.

 Functions:
  - my/sql-connect-postgres:     Connect to a PostgreSQL database, using an environment variable for the     password if available.
  - my/capture-sql-output:       Capture the last SQL query output and put it in a new buffer called \*SQL Results\*.
  - my/sql-save-history-hook:    Save-sql-history-dir defined in path-support.
  - my/upcase-sql-keywords:      Make all SQL keywords upper case.


#+begin_src emacs-lisp :tangle ./init.el

;; database integration and SQL support.
(require 'db-support)


#+end_src

Load the summary page code then set up the startup configuration.  Finalize the init log and profile the startup time.

 [[file:./custom-modules/menu-keys-support.el][Custom menu support]]:       Support for custom menus and keymaps. 
 [[file:./custom-modules/startup-config.el][Custom Startup configs]]:    Load the IDE on startup.

#+begin_src emacs-lisp :tangle ./init.el

  (require 'summary-support)
  (require 'system-window-management)
  (require 'startup-config)
  (require 'LLM-support)
  (require 'menu-keys-support)
  (require 'server-support)

;; All the autoloaded packages are now loaded.
;; set elisp-flymake-byte-compile-load-path
(setq elisp-flymake-byte-compile-load-path load-path)
(let  ((elisp-flymake-byte-compile-load-path-string
        (mapconcat 'identity elisp-flymake-byte-compile-load-path ";\n      ")))
  (log/info :fn 'init
            :msg "Set elisp-flymake-byte-compile-load-path"
            :obj (concat "(" elisp-flymake-byte-compile-load-path-string ")")))
#+end_src

Implement accounting functionality with hledger.

 [[file:./custom-modules/accounting-support.el][Accouting support]]:       Support for accounting features.  

#+begin_src emacs-lisp :tangle ./init.el

  (require 'accounting-support)
  
#+end_src


Show the loading time via a the emacs-startup-hook.

#+begin_src emacs-lisp :tangle ./init.el

;; ---------------------------------------------
;; All config and support files are now loaded.

;; Profile emacs startup
(defun my-startup/display-startup-time ()
  "Display the startup time after Emacs is fully initialized."
  (log/info :fn 'init
            :msg (format "Emacs loaded in %s." (emacs-init-time))
            :obj t))

(add-hook
 'emacs-startup-hook #'my-startup/display-startup-time)

(setq inhibit-startup-screen nil                                                 ; stop the default splash screen
      inhibit-startup-message nil
      inhibit-startup-echo-area-message nil)

(setq initial-scratch-message nil)                                             ; remove the message in the scratch buffer.


(recentf-mode 1)
(savehist-mode 1)

(provide 'init)
;;; init.el ends here

#+end_src


* Local Variables :noexport:
# Local Variables:
# visual-fill-column-width: 120
# End:
