;;; my-docs.el --- Documentation Tooling -*- lexical-binding: t; -*-

;; Copyright (C) 2023
;; SPDX-License-Identifier: MIT

;; Author: System Crafters Community (minor updates by Simon Watson, Aug 2026)

;;; Commentary:

;; This file is based off the work of System Crafters.  It provides a means of
;; producing custom documentation for an Emacs setup.

;; The file can be loaded to expose interactive functions in Emacs:
;; (load "[/path/to/emacs]/docs/my-docs.el")

;; You can evaluate this form directly:
;; (load (expand-file-name "docs/my-docs.el" user-emacs-directory))

;; EXPORT INFO FILE
;; The info file is best exported from a clean Emacs session.
;; This can be done from the command-line or from within Emacs.

;; Exporting from the command-line can be accomplished by running `make'.
;; The Makefile will only generate the info file if any of the org files
;; changed.

;; Alternatively, if you don't want to use `make',
;; you can run the command manually (assuming you're in docs/):
;;     emacs -Q --script my-docs.el -f my-docs-export-info

;;; Code:

(require 'ox-texinfo)

(defvar my-docs-directory (expand-file-name "docs/" user-emacs-directory)
  "The path to documentation for my emacs setup.")

;;; Info file export
(defun my-docs-export-info ()
  "Export crafted-emacs.info file from crafted-emacs.org in current directory.
Remove intermediate texi file (generated by texinfo)."
  (with-current-buffer (find-file "./crafted-emacs.org")
    (org-texinfo-export-to-info))
  (delete-file "./crafted-emacs.texi")
  (message "Generated crafted-emacs.info file"))

(defvar my-docs-export-use-user-emacs-directory nil
  "Find the documentation directory.

If set non-nil, search in the directory specified by `user-emacs-directory'
for the documentation directory when running `my-docs-export'.")

(defun my-docs-export--sentinel (proc event)
  "Sentinel for `my-docs-export' providing customized message feedback.
PROC and EVENT are passed by `make-process' where PROC is unused here and
EVENT contains the standard event-text."
  (cond ((string-match-p "finished" event)
         (message "Emacs: docs export finished"))
        ((string-match-p "exited.*" event)
         (message "Emacs Docs export %s. See *my-docs-export* buffer for more information"
                  event))))

(defun my-docs-export (&optional my-docs-directory)
  "Export crafted-emacs.info file in a separate Emacs session.

Unless passed as MY-DOCS-DIRECTORY,
attempt to find the Crafted Emacs docs directory.
The current directory is checked first.
If `my-docs-export-use-user-emacs-directory' is non-nil and
`user-emacs-directory' is an existing directory, use the `docs' sub-directory
there.
If none of the above produce a directory, prompt the user to specify the docs
directory using `read-directory-name'.

This does not utilize make, instead running Emacs as a separate process
directly.

If you want to use the Makefile, look at the `compile' command.

Export output is written to the *my-docs-export* buffer."
  (interactive
   (list
    (cond ((file-exists-p "./my-docs.el") ".")
          ((and my-docs-export-use-user-emacs-directory
                (boundp 'user-emacs-directory)
                (file-directory-p user-emacs-directory))
           (expand-file-name "docs/" user-emacs-directory))
          (t (read-directory-name "Crafted Emacs docs-directory: ")))))

  (unless (executable-find "emacs")
    (user-error "Emacs is not in PATH"))

  (let ((docs-directory (expand-file-name my-docs-directory))
        (docs-script (expand-file-name "my-docs.el"
                                       my-docs-directory)))
    (if (file-exists-p docs-script)
        (make-process :name "my-docs-export"
                      :buffer "*my-docs-export*"
                      :command (list "emacs"
                                     "-Q" "--script" "my-docs.el"
                                     "--chdir" docs-directory
                                     "--funcall" "my-docs-export-info")
                      :sentinel #'my-docs-export--sentinel)
      (user-error "Directory %s is not the Emacs docs directory"
                  docs-directory))))

(provide 'my-docs)
;;; my-docs.el ends here

